---
# Items that apply to ALL profiles:
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8011/eureka/

---
spring:
  data:
    mongodb:
      uri: mongodb://localhost:37017/microservice

---
---
# spring:
#   datasource:
#      hikari:
#       jdbc-url: jdbc:h2:~/testdb
    
   
#   jpa:
#    show-sql: true

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/microservice
    username: admin
    password: admin
  jpa:
   show-sql: true
   hibernate.ddl-auto: update

---
spring:
  cloud:
    stream:
      bindings:
        paymentsChannel:
         binder: rabbit
         destination: newpayment.ms.exchange
         content-type: application/json
         group: microservice.services  

---
spring:
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      percentage: 1.0   
app.service-name: User Service - Updated to ananya

        


